### ISSUE TITLE
1.3.1 on npm

### ISSUE THREAD

**Issue by matthewma7** [nyxtom/reconcile.js#7]
Hi @nyxtom,

I saw you released a version to npm, but it seems the **assume-no-change** feature is not include?
I am not so familar with npm release, did I missed something?

Sincerely,

**Comment by nyxtom** [comment]
Oh the issue is the changes were made to reconcile.umd.js rather than lib/reconcile.js

**Comment by matthewma7** [comment]
Oh, ok. I'll create a new PR to revert and change and apply the change to lib/reconcile.js

**Comment by matthewma7** [comment]
A new version is released with the feature. Closing issue. 
Thanks, @nyxtom
